---
baseURL: https://digisec.directory/
title: digisec.directory
theme: hugo-geekdoc

pygmentsUseClasses: true
pygmentsCodeFences: true
timeout: 180000
pluralizeListTitles: false

defaultContentLanguage: global

disablePathToLower: true
enableGitInfo: true

enableRobotsTXT: true

paginate: 100000

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
    endLevel: 9

taxonomies:
  flag: flags
  tag: tags
  category: categories
  language: languages

outputs:
  home:
    - HTML
  page:
    - HTML
  section:
    - HTML
  taxonomy:
    - HTML
  term:
    - HTML

security:
  exec:
    allow:
      - "^asciidoctor$"