---
en:
  languageName: "English"
  contentDir: "content/en"
  weight: 10
fil:
  languageName: "Filipino"
  contentDir: "content/fil"
  weight: 10
id:
  languageName: "Bahasa Indonesia (Indonesian)"
  contentDir: "content/id"
  weight: 10
km:
  languageName: "ភាសាខ្មែរ (Khmer)"
  contentDir: "content/km"
  weight: 10
my:
  languageName: "မြန်မာဘာသာ (Burmese)"
  contentDir: "content/my"
  weight: 10
th:
  languageName: "ไทย (Thai)"
  contentDir: "content/th"
  weight: 10
---