---
geekdocToC: 3

geekdocLogo: files/digisec.directory.svg
geekdocMenuBundle: true
geekdocCollapseAllSections: false

geekdocNextPrev: false
geekdocBreadcrumb: false

#geekdocRepo: 'https://gitlab.com/-/ide/project/eml10n/digisecdirectory'
#geekdocEditPath: edit/main/-

geekdocSearch: false
geekdocSearchShowParent: true

#geekdocPrivacyPolicy: /privacy/

geekdocAnchor: true
geekdocAnchorCopy: true

geekdocImageLazyLoading: true
geekdocOverwriteHTMLBase: false
geekdocDarkModeDim: false
geekdocDarkModeCode: false

geekdocBackToTop: true

geekdocTagsToMenu: false

geekdocFileTreeSortBy: title
---