---

geekdocToC: 3
geekdocTagsToMenu: true

geekdocRepo: https://gitlab.com/-/ide/project/eml10n/digisecdirectory
geekdocEditPath: edit/hugo/-

geekdocSearch: true
geekdocSearchShowParent: true
geekdocSearchShowDescription: true

geekdocLegalNotice: https://thegeeklab.de/legal-notice/#contact-information
geekdocPrivacyPolicy: https://thegeeklab.de/legal-notice/#privacy-policy

geekdocImageLazyLoading: true
geekdocDarkModeDim: true

---