backend:
  name: git-gateway
  branch: main
media_folder: static/files
public_folder: /files
site_url: https://digisec.directory
display_url: https://digisec.directory
collections:
  - name: 'content-en'
    label: 'English Content'
    folder: 'content/en'
    filter:
      field: type
      value: post
    create: true
    slug: '{{slug}}'
    preview_path: '{{filename}}'
    editor:
      preview: false
    show_preview_links: true
    fields:
      - label: 'Type'
        name: 'type'
        widget: 'hidden'
        default: 'post'
      - label: 'Title' 
        name: 'title' 
        widget: 'string'
      - label: 'Cover Image'
        name: 'cover'
        widget: 'image'
        required: false
      - label: 'Body'
        name: 'body' 
        widget: 'markdown'
      - label: 'Credits'
        name: 'credits' 
        widget: 'text'
      - label: 'Tags'
        name: 'tags'
        widget: 'select'
        multiple: true
        options:
          - Circumvention and Anonymity
          - Communications and Messaging
          - Documentation and Data Management
          - Productivity and Browser
          - Protecting Privacy
          - Enhancing Security
          - Improving Wellbeing
          - Identifying Misinformation
        required: true
      - label: 'Category'
        name: 'category'
        widget: 'select'
        options:
          - Digital Security Guides
          - Digital Security Tools
        required: true
      - label: 'Date & Time'
        name: 'date'
        widget: 'datetime'
      - label: 'Aliases'
        name: 'aliases'
        widget: 'list'
      - label: 'HTML Meta Description'
        name: 'description'
        widget: 'string'
        required: false
      - label: 'HTML Meta Keywords'
        name: 'keywords'
        widget: 'list'
        required: false
    sortable_fields: 
      - title
      - date
    view_filters:
      - label: "Circumvention and Anonymity"
        field: tag
        pattern: 'circumvention'
      - label: 'Communications and Messaging'
        field: tag
        pattern: 'communications'
      - label: 'Documentation and Data Management'
        field: tag
        pattern: 'documentation'
      - label: 'Productivity and Browser'
        field: tag
        pattern: 'productivity'
      - label: 'Digital Security Guides'
        field: category
        pattern: 'guides'
      - label: 'Digital Security Tools'
        field: category
        pattern: 'tools'