backend:
  name: gitlab
  repo: eml10n/digisecdirectory
  branch: main
  base_url: https://digisec.directory
  auth_endpoint: /auth-start
media_folder: static/files
public_folder: /files
site_url: https://digisec.directory
display_url: https://digisec.directory
collections:
  - name: 'tools'
    label: 'Digital Security Tools'
    folder: 'content/en/tools'
    create: true
    slug: '{{slug}}'
    preview_path: '{{filename}}'
    editor:
      preview: false
    show_preview_links: true
    fields:
      - label: 'Title' 
        name: 'title' 
        widget: 'string'
      - label: 'Languages' 
        name: 'languages' 
        comment: 'Before you add, verify that the language is supported. Use ISO 639-1 code only without country code. ms instead of ms_MY. If the source language is English, do not add to the list.'
        widget: 'list'
        allow_add: true
        default:
          - en
        options:
          - en
          - fil
          - id
          - km
          - my
          - th
      - label: 'Website'
        name: 'website'
        widget: 'string'
        required: true
      - label: 'Body'
        name: 'body' 
        widget: 'markdown'
      - label: 'Cover Image'
        name: 'cover'
        widget: 'image'
        required: true
      - label: 'Tags'
        name: 'tags'
        widget: 'select'
        multiple: true
        options:
          # Flags
          - Open Source 
          - Closed Source 
          - Free 
          - Freemium 
          - Premium 

          # Digital Security Tools
          - Circumvention and Anonymity
          - Communications and Messaging
          - Documentation and Data Management
          - Productivity and Browser

          # Digital Safety Guides
          - Protecting Privacy
          - Enhancing Security
          - Improving Wellbeing
          - Identifying Misinformation
        required: true
      - label: 'Credits'
        name: 'credits' 
        widget: 'string'
        required: false
      - label: 'Date & Time'
        name: 'date'
        widget: 'datetime'
    sortable_fields: 
      - title
      - date
    view_filters:
      # Flags
      - pattern: Closed Source 
        label: Closed Source 
        field: tag
      - pattern: Open Source 
        label: Open Source 
        field: tag
      - pattern: Free 
        label: Free 
        field: tag
      - pattern: Freemium 
        label: Freemium 
        field: tag
      - pattern: Premium 
        label: Premium 
        field: tag

      # Digital Security Tools
      - pattern: "Circumvention and Anonymity"
        label: "Circumvention and Anonymity"
        field: tag
      - pattern: 'Communications and Messaging'
        label: 'Communications and Messaging'
        field: tag
      - pattern: 'Documentation and Data Management'
        label: 'Documentation and Data Management'
        field: tag
      - pattern: 'Productivity and Browser'
        label: 'Productivity and Browser'
        field: tag

      # Digital Safety Guides
      - pattern: Protecting Privacy
        label: Protecting Privacy
        field: tag
      - pattern: Enhancing Security
        label: Enhancing Security
        field: tag
      - pattern: Improving Wellbeing
        label: Improving Wellbeing
        field: tag
      - pattern: Identifying Misinformation
        label: Identifying Misinformation
        field: tag
