backend:
 name: gitlab
 repo: eml10n/digisecdirectory # Path to your GitLab repository
 branch: main
 auth_type: pkce # Required for pkce
 app_id: 7211b2bd14325e647d848c9d5dbee2f65e8899b7160f05b9ef657a54cabb2e21 # Application ID from your GitLab settings
 cms_label_prefix: netlify-cms/
 preview_context: review/cms-blog-posts-{{file_name}}
# publish_mode: editorial_workflow
media_folder: static/files
public_folder: /files
site_url: https://digisec.directory
logo_url: "/favicon/favicon.svg"
collections:
# Digital Security Tools
  - name: 'tools'
    label: 'Digital Security Tools' # OK TO TRANLSATE
    label_singular: 'Digital Security Tool' # OK TO TRANLSATE
    folder: 'content/en'
    create: true
    filter:
      field: categories
      value: 'Digital Security Tools' # OK TO TRANLSATE
    slug: '{{slug}}'
    preview_path: '{{filename}}'
    editor:
      preview: false
    show_preview_links: true
    fields:
      - label: 'Name' # OK TO TRANLSATE
        name: 'title' 
        widget: 'string'
      - label: 'Icon' # OK TO TRANLSATE
        name: 'cover'
        widget: 'image'
        required: true
      - label: 'Supported Languages' # OK TO TRANLSATE
        name: 'languages' 
        comment: 'Verify that the language is supported before adding its ISO 639-1 code here. without the country code, i.e. ms instead of ms_MY.'
        description: 'Verify that the language is supported before adding its ISO 639-1 code here. without the country code, i.e. ms instead of ms_MY.'
        widget: 'select'
        multiple: true
        allow_add: true
        default:
          - en # English
        options:
          # Official ASEAN languages
          - my # Burmese
          - zh # Chinese
          - en # English
          - fil # Filipino
          - id # Indonesian
          - km # Khmer
          - lo # Lao
          - ms # Malay
          - ta # Tamil
          - th # Thai
          - vi # Vietnamese

          # Other EngageMedia langauges
          - bn # Bengali
          - hi # Hindi
          - ur # Urdu

      - label: 'Website' # OK TO TRANLSATE
        name: 'website'
        widget: 'string'
        required: true
      - label: 'Description' # OK TO TRANLSATE
        name: 'body'
        widget: 'markdown'
      - label: 'Credits'
        name: 'credits' 
        widget: 'string'
        required: false
      - label: 'Flags' # OK TO TRANLSATE
        name: 'flags'
        widget: 'select'
        multiple: true
        options:
          - Closed Source # OK TO TRANLSATE
          - Freemium # OK TO TRANLSATE
          - Premium # OK TO TRANLSATE

        required: false
      - label: 'Tags' # OK TO TRANLSATE
        name: 'tags'
        widget: 'select'
        multiple: true
        options:
          - Web App # OK TO TRANLSATE
          - Self-hosting # OK TO TRANLSATE
          - Cross-platform # OK TO TRANLSATE

          # Digital Security Tools
          - Circumvention & Anonymity # OK TO TRANLSATE
          - Communications & Messaging # OK TO TRANLSATE
          - Documentation & Data Management # OK TO TRANLSATE
          - Productivity & Browser # OK TO TRANLSATE
          
        required: true
      - label: 'Categories' # OK TO TRANLSATE
        name: 'categories'
        widget: 'select'
        multiple: true
        default: Digital Security Tools
        options:
          # Primary categories
          - Digital Security Guides # OK TO TRANLSATE 
          - Digital Security Tools # OK TO TRANLSATE
          - Digital Security Network # OK TO TRANLSATE

          # Secondary categories
          - File Sharing # OK TO TRANLSATE 
          - File Storage # OK TO TRANLSATE 
          - File Sync # OK TO TRANLSATE 
          - Instant Messaging # OK TO TRANLSATE 
          - Onion Routing # OK TO TRANLSATE 
          - OpenPGP Encryption # OK TO TRANLSATE 
          - Password Management # OK TO TRANLSATE 
          - Videoconferencing # OK TO TRANLSATE 
          - Virtual Private Network # OK TO TRANLSATE 
      - label: 'Date & Time' # OK TO TRANLSATE 
        name: 'date'
        widget: 'datetime'
    sortable_fields: 
      - title
      - date

  # Digital Security Guides    
  - name: 'guides'
    label: 'Digital Security Guides' # OK TO TRANLSATE 
    label_singular: 'Digital Security Guides' # OK TO TRANLSATE 
    folder: 'content/en'
    create: true
    filter:
      field: categories
      value: 'Digital Security Guides' # OK TO TRANLSATE 
    slug: '{{slug}}'
    preview_path: '{{filename}}'
    editor:
      preview: false
    show_preview_links: true
    fields:
      - label: 'Title' # OK TO TRANLSATE 
        name: 'title' 
        widget: 'string'
      - label: 'Supported Languages' # OK TO TRANLSATE 
        name: 'languages' 
        comment: 'Verify that the language is supported before adding its ISO 639-1 code here. without the country code, i.e. ms instead of ms_MY.'
        description: 'Verify that the language is supported before adding its ISO 639-1 code here. without the country code, i.e. ms instead of ms_MY.'
        widget: 'select'
        multiple: true
        allow_add: true
        default:
          - en
        options:
          # Official ASEAN languages
          - my # Burmese
          - zh # Chinese
          - en # English
          - fil # Filipino
          - id # Indonesian
          - km # Khmer
          - lo # Lao
          - ms # Malay
          - ta # Tamil
          - th # Thai
          - vi # Vietnamese

          # Other EngageMedia langauges
          - bn # Bengali
          - hi # Hindi
          - ur # Urdu

      - label: 'Website' # OK TO TRANLSATE 
        name: 'website'
        widget: 'string'
        required: true
      - label: 'Summary' # OK TO TRANLSATE 
        name: 'body'
        widget: 'markdown'
      - label: 'Credits' # OK TO TRANLSATE 
        name: 'credits' 
        default: ''
        widget: 'string'
        required: false
      - label: 'Flags' # OK TO TRANLSATE
        name: 'flags'
        widget: 'select'
        multiple: true
        options:
          - PDF # OK TO TRANLSATE
        required: false
      - label: 'Categories' # OK TO TRANLSATE 
        name: 'categories'
        widget: 'select'
        multiple: true
        default: Digital Security Guides # OK TO TRANLSATE 
        options:
          # Primary categories
          - Digital Security Guides # OK TO TRANLSATE 
          - Digital Security Tools # OK TO TRANLSATE 
          - Digital Security Network # OK TO TRANLSATE 
      - label: 'Date & Time' # OK TO TRANLSATE 
        name: 'date'
        widget: 'datetime'
    sortable_fields: 
      - title
      - date

  # Digital Security Network
  - name: 'network'
    label: 'Digital Security Network' # OK TO TRANLSATE 
    label_singular: 'Digital Security Network Organisation' # OK TO TRANLSATE 
    folder: 'content/en'
    create: true
    filter:
      field: categories
      value: 'Digital Security Network' # OK TO TRANLSATE 
    slug: '{{slug}}'
    preview_path: '{{filename}}'
    editor:
      preview: false
    show_preview_links: true
    fields:
      - label: 'Name' # OK TO TRANLSATE 
        name: 'title' 
        widget: 'string'
      - label: 'Logo' # OK TO TRANLSATE 
        name: 'cover'
        widget: 'image'
      - label: 'Supported Languages' # OK TO TRANLSATE 
        name: 'languages' 
        comment: 'Verify that the language is supported before adding its ISO 639-1 code here. without the country code, i.e. ms instead of ms_MY.'
        description: 'Verify that the language is supported before adding its ISO 639-1 code here. without the country code, i.e. ms instead of ms_MY.'
        widget: 'select'
        multiple: true
        allow_add: true
        default:
          - en
        options:
          # Official ASEAN languages
          - my # Burmese
          - zh # Chinese
          - en # English
          - fil # Filipino
          - id # Indonesian
          - km # Khmer
          - lo # Lao
          - ms # Malay
          - ta # Tamil
          - th # Thai
          - vi # Vietnamese

          # Other EngageMedia langauges
          - bn # Bengali
          - hi # Hindi
          - ur # Urdu
          
      - label: 'Website' # OK TO TRANLSATE 
        name: 'website'
        widget: 'string'
        required: true
      - label: 'Description' # OK TO TRANLSATE 
        name: 'body'
        widget: 'markdown'
      - label: 'Credits'
        name: 'credits' 
        default: ''
        widget: 'string'
        required: false
      - label: 'Categories' # OK TO TRANLSATE 
        name: 'categories'
        widget: 'select'
        multiple: true
        default: Digital Security Network # OK TO TRANLSATE 
        options:
          # Primary categories
          - Digital Security Guides # OK TO TRANLSATE 
          - Digital Security Tools # OK TO TRANLSATE 
          - Digital Security Network # OK TO TRANLSATE 

          # Digital Security Network categories
          - Digital Security Crisis Responders # OK TO TRANLSATE 
          - Digital Security Service Providers # OK TO TRANLSATE 
          - Digital Security Trainers # OK TO TRANLSATE 
      - label: 'Date & Time'
        name: 'date'
        widget: 'datetime'
    sortable_fields: 
      - title
      - date


# Other
  - name: 'pages'
    label: 'Pages' # OK TO TRANLSATE 
    label_singular: 'Page' # OK TO TRANLSATE 
    folder: 'content/en'
    create: true
    filter:
      field: type
      value: 'page'
    slug: '{{slug}}'
    preview_path: '{{filename}}'
    editor:
      preview: false
    show_preview_links: true
    fields:
      - name: 'type'
        widget: 'hidden'
        default: 'page'
      - label: 'Title' # OK TO TRANLSATE  
        name: 'title' 
        widget: 'string'
      - label: 'Content' # OK TO TRANLSATE  
        name: 'body' 
        widget: 'markdown'
      - label: 'Date & Time' # OK TO TRANLSATE 
        name: 'date'
        widget: 'datetime'