backend:
 name: gitlab
 repo: eml10n/digisecdirectory # Path to your GitLab repository
 branch: main
 auth_type: pkce # Required for pkce
 app_id: 7211b2bd14325e647d848c9d5dbee2f65e8899b7160f05b9ef657a54cabb2e21 # Application ID from your GitLab settings
 cms_label_prefix: netlify-cms/
 preview_context: review/cms-blog-posts-{{file_name}}  # MR !78973
publish_mode: editorial_workflow
media_folder: static/files
public_folder: /files
site_url: https://digisec.directory
logo_url: "/files/digisec.directory.svg"
i18n:
  structure: multiple_folders
  locales:
    - en
    - fil
    - id
    - km
    - my
    - th
default_locale: en
collections:
  - name: 'tools'
    label: 'Digital Security Tools'
    label_singular: 'Digital Security Tool'
    folder: 'content'
    create: true
    filter:
      field: categories
      value: 'Digital Security Tools'
    slug: '{{slug}}'
    preview_path: '{{filename}}'
    editor:
      preview: false
    show_preview_links: true
    i18n: true
    fields:
      - label: 'Name' 
        name: 'title' 
        i18n: duplicate
        widget: 'string'
      - label: 'Icon'
        name: 'cover'
        i18n: duplicate
        widget: 'image'
        required: true
      - label: 'Supported Languages' 
        name: 'languages' 
        i18n: duplicate
        comment: 'Verify that the language is supported before adding its ISO 639-1 code here. without the country code, i.e. ms instead of ms_MY.'
        description: 'Verify that the language is supported before adding its ISO 639-1 code here. without the country code, i.e. ms instead of ms_MY.'
        widget: 'select'
        multiple: true
        allow_add: true
        default:
          - en
        options:
          - en
          - fil
          - id
          - km
          - my
          - th
      - label: 'Website'
        name: 'website'
        i18n: duplicate
        widget: 'string'
        required: true
      - label: 'Body'
        name: 'body'
        i18n: true
        widget: 'markdown'
      - label: 'Credits'
        name: 'credits' 
        i18n: true
        default: 'Text by EngageMedia.'
        widget: 'string'
        required: false
      - label: 'Tags'
        name: 'tags'
        i18n: duplicate
        widget: 'select'
        multiple: true
        options:
          # Red Flags
          - Closed Source 
          - Freemium 

          # Green Flags
          - Web App 
          - Self-hosting 

          # Digital Security Tools
          - Circumvention & Anonymity
          - Communications & Messaging
          - Documentation & Data Management
          - Productivity & Browser

          # Digital Safety Guides
          - Protecting Privacy
          - Enhancing Security
          - Improving Wellbeing
          - Countering Misinformation

          # Formats
          - Video
          - Infographic
          - Online Course

          # Other Resources
          - Training 
          - Crisis Response

        required: true
      - label: 'Categories'
        name: 'categories'
        i18n: duplicate
        widget: 'select'
        multiple: true
        default: Digital Security Tools
        options:
          # Primary categories
          - Digital Safety Guides 
          - Digital Security Tools

          # Secondary categories
          - File Sharing # Alternative to We Transfer
          - File Storage & Sync # Alternative to Google Drive, Dropbox
          - Instant Messaging # Alternative to WhatsApp
          - Onion Routing
          - OpenPGP Encryption
          - Password Management
          - Videoconferencing # Alternative to Zoom
          - Virtual Private Network
      - label: 'Date & Time'
        name: 'date'
        widget: 'datetime'
    sortable_fields: 
      - title
      - date
    view_filters:
      # Red Flags
      - pattern: Closed Source 
        label: Closed Source 
        field: tags
      - pattern: Freemium 
        label: Freemium 
        field: tags

      # Green Flags
      - pattern: Web App 
        label: Web App 
        field: tags
      - pattern: Self-hosting 
        label: Self-hosting 
        field: tags

      # Digital Security Tools
      - pattern: "Circumvention & Anonymity"
        label: "Circumvention & Anonymity"
        field: tags
      - pattern: 'Communications & Messaging'
        label: 'Communications & Messaging'
        field: tags
      - pattern: 'Documentation & Data Management'
        label: 'Documentation & Data Management'
        field: tags
      - pattern: 'Productivity & Browser'
        label: 'Productivity & Browser'
        field: tags

      # Secondary categories
      - pattern: File Sharing # Alternative to We Transfer
        label: File Sharing # Alternative to We Transfer
        field: categories
      - pattern: File Storage & Sync # Alternative to Google Drive, Dropbox
        label: File Storage & Sync # Alternative to Google Drive, Dropbox
        field: categories
      - pattern: Instant Messaging # Alternative to WhatsApp
        label: Instant Messaging # Alternative to WhatsApp
        field: categories
      - pattern: Onion Routing
        label: Onion Routing
        field: categories
      - pattern: OpenPGP Encryption
        label: OpenPGP Encryption
        field: categories
      - pattern: Password Management
        label: Password Management
        field: categories
      - pattern: Videoconferencing # Alternative to Zoom
        label: Videoconferencing # Alternative to Zoom
        field: categories
      - pattern: Virtual Private Network
        label: Virtual Private Network
        field: categories

      # Digital Safety Guides
      - pattern: Enhancing Security
        label: Enhancing Security
        field: tags
      - pattern: Protecting Privacy
        label: Protecting Privacy
        field: tags
      - pattern: Improving Wellbeing
        label: Improving Wellbeing
        field: tags
      - pattern: Countering Misinformation
        label: Countering Misinformation
        field: tags
