backend:
 name: gitlab
 repo: eml10n/digisecdirectory # Path to your GitLab repository
 branch: main
 auth_type: pkce # Required for pkce
 app_id: 7211b2bd14325e647d848c9d5dbee2f65e8899b7160f05b9ef657a54cabb2e21 # Application ID from your GitLab settings
 cms_label_prefix: netlify-cms/
 preview_context: review/cms-blog-posts-{{file_name}}
# publish_mode: editorial_workflow
media_folder: static/files
public_folder: /files
site_url: https://digisec.directory
logo_url: "/files/digisec.directory.svg"
collections:
# Digital Security Tools
  - name: 'tools'
    label: 'Digital Security Tools'
    label_singular: 'Digital Security Tool'
    folder: 'content'
    create: true
    filter:
      field: categories
      value: 'Digital Security Tools'
    slug: '{{slug}}'
    preview_path: '{{filename}}'
    editor:
      preview: false
    show_preview_links: true
    fields:
      - label: 'Name' 
        name: 'title' 
        widget: 'string'
      - label: 'Icon'
        name: 'cover'
        widget: 'image'
        required: true
      - label: 'Supported Languages' 
        name: 'languages' 
        comment: 'Verify that the language is supported before adding its ISO 639-1 code here. without the country code, i.e. ms instead of ms_MY.'
        description: 'Verify that the language is supported before adding its ISO 639-1 code here. without the country code, i.e. ms instead of ms_MY.'
        widget: 'select'
        multiple: true
        allow_add: true
        default:
          - en # English
        options:
          # Official ASEAN languages
          - my # Burmese
          - zh # Chinese
          - en # English
          - fil # Filipino
          - id # Indonesian
          - km # Khmer
          - lo # Lao
          - ms # Malay
          - ta # Tamil
          - th # Thai
          - vi # Vietnamese

          # Other EngageMedia langauges
          - bn # Bengali
          - hi # Hindi
          - ur # Urdu

      - label: 'Website'
        name: 'website'
        widget: 'string'
        required: true
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
      - label: 'Credits'
        name: 'credits' 
        default: 'Text by EngageMedia.'
        widget: 'string'
        required: false
      - label: 'Tags'
        name: 'tags'
        widget: 'select'
        multiple: true
        options:
          # Red Flags
          - Closed Source 
          - Freemium 

          # Green Flags
          - Web App 
          - Self-hosting 

          # Digital Security Tools
          - Circumvention & Anonymity
          - Communications & Messaging
          - Documentation & Data Management
          - Productivity & Browser

          # Formats
          - Video
          - Infographic
          - Online Course

          # Other Resources
          - Training 
          - Crisis Response

        required: true
      - label: 'Categories'
        name: 'categories'
        widget: 'select'
        multiple: true
        default: Digital Security Tools
        options:
          # Primary categories
          - Digital Security Guides 
          - Digital Security Tools
          - Network Resources

          # Secondary categories
          - File Sharing # Alternative to We Transfer
          - File Storage & Sync # Alternative to Google Drive, Dropbox
          - Instant Messaging # Alternative to WhatsApp
          - Onion Routing
          - OpenPGP Encryption
          - Password Management
          - Videoconferencing # Alternative to Zoom
          - Virtual Private Network
      - label: 'Date & Time'
        name: 'date'
        widget: 'datetime'
    sortable_fields: 
      - title
      - date

  # Digital Security Guides    
  - name: 'guides'
    label: 'Digital Security Guides'
    label_singular: 'Digital Security Guides'
    folder: 'content'
    create: true
    filter:
      field: categories
      value: 'Digital Security Guides'
    slug: '{{slug}}'
    preview_path: '{{filename}}'
    editor:
      preview: false
    show_preview_links: true
    fields:
      - label: 'Title' 
        name: 'title' 
        widget: 'string'
      - label: 'Supported Languages' 
        name: 'languages' 
        comment: 'Verify that the language is supported before adding its ISO 639-1 code here. without the country code, i.e. ms instead of ms_MY.'
        description: 'Verify that the language is supported before adding its ISO 639-1 code here. without the country code, i.e. ms instead of ms_MY.'
        widget: 'select'
        multiple: true
        allow_add: true
        default:
          - en
        options:
          # Official ASEAN languages
          - my # Burmese
          - zh # Chinese
          - en # English
          - fil # Filipino
          - id # Indonesian
          - km # Khmer
          - lo # Lao
          - ms # Malay
          - ta # Tamil
          - th # Thai
          - vi # Vietnamese

          # Other EngageMedia langauges
          - bn # Bengali
          - hi # Hindi
          - ur # Urdu

      - label: 'Website'
        name: 'website'
        widget: 'string'
        required: true
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
      - label: 'Credits'
        name: 'credits' 
        default: ''
        widget: 'string'
        required: false
      - label: 'Categories'
        name: 'categories'
        widget: 'select'
        multiple: true
        default: Digital Security Guides
        options:
          # Primary categories
          - Digital Security Guides 
          - Digital Security Tools
          - Network Resources
      - label: 'Date & Time'
        name: 'date'
        widget: 'datetime'
    sortable_fields: 
      - title
      - date

  # Digital Security Network
  - name: 'network'
    label: 'Digital Security Network'
    label_singular: 'Digital Security Network'
    folder: 'content'
    create: true
    filter:
      field: categories
      value: 'Digital Security Network'
    slug: '{{slug}}'
    preview_path: '{{filename}}'
    editor:
      preview: false
    show_preview_links: true
    fields:
      - label: 'Name' 
        name: 'title' 
        widget: 'string'
      - label: 'Logo'
        name: 'cover'
        widget: 'image'
      - label: 'Supported Languages' 
        name: 'languages' 
        comment: 'Verify that the language is supported before adding its ISO 639-1 code here. without the country code, i.e. ms instead of ms_MY.'
        description: 'Verify that the language is supported before adding its ISO 639-1 code here. without the country code, i.e. ms instead of ms_MY.'
        widget: 'select'
        multiple: true
        allow_add: true
        default:
          - en
        options:
          # Official ASEAN languages
          - my # Burmese
          - zh # Chinese
          - en # English
          - fil # Filipino
          - id # Indonesian
          - km # Khmer
          - lo # Lao
          - ms # Malay
          - ta # Tamil
          - th # Thai
          - vi # Vietnamese

          # Other EngageMedia langauges
          - bn # Bengali
          - hi # Hindi
          - ur # Urdu
          
      - label: 'Website'
        name: 'website'
        widget: 'string'
        required: true
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
      - label: 'Credits'
        name: 'credits' 
        default: ''
        widget: 'string'
        required: false
      - label: 'Categories'
        name: 'categories'
        widget: 'select'
        multiple: true
        default: Digital Security Network
        options:
          # Primary categories
          - Digital Security Guides 
          - Digital Security Tools
          - Digital Security Network

          # Digital Security Network categories
          - Digital Security Auditors
          - Digital Security Crisis Responders
          - Digital Security Service Providers
          - Digital Security Trainers
      - label: 'Date & Time'
        name: 'date'
        widget: 'datetime'
    sortable_fields: 
      - title
      - date