backend:
  name: git-gateway
  branch: main
media_folder: static/files
public_folder: /files
site_url: https://digisec.directory
display_url: https://digisec.directory
collections:
  - name: 'tools'
    label: 'Digital Security Tools'
    folder: 'content/en'
    create: true
    filter:
      field: categories
      value: 'Digital Security Tools'
    slug: '{{slug}}'
    preview_path: '{{filename}}'
    editor:
      preview: false
    show_preview_links: true
    fields:
      - label: 'Draft' 
        name: 'draft' 
        widget: 'boolean'
        default: false
        required: false
      - label: 'Name' 
        name: 'title' 
        widget: 'string'
      - label: 'Languages' 
        name: 'languages' 
        comment: 'Before you add, verify that the language is supported. Use ISO 639-1 code only without country code. ms instead of ms_MY. If the source language is English, do not add to the list.'
        widget: 'select'
        multiple: true
        allow_add: true
        default:
          - en
        options:
          - en
          - fil
          - id
          - km
          - my
          - th
      - label: 'Website'
        name: 'website'
        widget: 'string'
        required: true
      - label: 'Body'
        name: 'body' 
        widget: 'markdown'
      - label: 'Icon'
        name: 'cover'
        widget: 'image'
        required: true
      - label: 'Tags'
        name: 'tags'
        widget: 'select'
        multiple: true
        options:
          # Red Flags
          - Closed Source 
          - Freemium 

          # Green Flags
          - Web App 
          - Self-hosting 

          # Digital Security Tools
          - Circumvention & Anonymity
          - Communications & Messaging
          - Documentation & Data Management
          - Productivity & Browser

          # Digital Safety Guides
          - Protecting Privacy
          - Enhancing Security
          - Improving Wellbeing
          - Countering Misinformation

          # Formats
          - Video
          - Infographic
          - Online Course

          # Other Resources
          - Training 
          - Crisis Response

        required: true
      - label: 'Categories'
        name: 'categories'
        widget: 'select'
        multiple: true
        default: Digital Security Tools
        options:
          # Primary categories
          - Digital Safety Guides 
          - Digital Security Tools

          # Secondary categories
          - File Sharing # Alternative to We Transfer
          - File Storage & Sync # Alternative to Google Drive, Dropbox
          - Instant Messaging # Alternative to WhatsApp
          - Onion Network
          - Password Management
          - Videoconferencing # Alternative to Zoom
          - Virtual Private Network
      - label: 'Credits'
        name: 'credits' 
        default: 'Text by EngageMedia.'
        widget: 'string'
        required: false
      - label: 'Date & Time'
        name: 'date'
        widget: 'datetime'
    sortable_fields: 
      - title
      - date
    view_filters:
      # Red Flags
      - pattern: Closed Source 
        label: Closed Source 
        field: tags
      - pattern: Freemium 
        label: Freemium 
        field: tags

      # Green Flags
      - pattern: Web App 
        label: Web App 
        field: tags
      - pattern: Self-hosting 
        label: Self-hosting 
        field: tags

      # Digital Security Tools
      - pattern: "Circumvention & Anonymity"
        label: "Circumvention & Anonymity"
        field: tags
      - pattern: 'Communications & Messaging'
        label: 'Communications & Messaging'
        field: tags
      - pattern: 'Documentation & Data Management'
        label: 'Documentation & Data Management'
        field: tags
      - pattern: 'Productivity & Browser'
        label: 'Productivity & Browser'
        field: tags

      # Digital Safety Guides
      - pattern: Enhancing Security
        label: Enhancing Security
        field: tags
      - pattern: Protecting Privacy
        label: Protecting Privacy
        field: tags
      - pattern: Improving Wellbeing
        label: Improving Wellbeing
        field: tags
      - pattern: Countering Misinformation
        label: Countering Misinformation
        field: tag
